### ISSUE TITLE
Dude Where's My Horse - reed flute recipe

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/RTTS-Atum#23]
Doesn't work. When trying to autocraft it registered the reeds as the item missing (and also has a different texture icon for them, so maybe there's 2 textures of reeds and it's confusing them? Not sure...)

![](https://cdn.discordapp.com/attachments/308301474847391744/578676294053527584/unknown.png)

**Comment by Shadowclaimer** [comment]
Self note: Needs changed to papyrus_plant from papyrus because the plant is the item.
