### ISSUE TITLE
Reed Flute

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/RTTS-Atum#27]
this bug only exists in multiplayer for some reason, maybe because we have so many tamed camels?

the pipe is supposed to teleport the nearest saddled mount to you, but instead it just lists nearby mounts. This is the same function for shift right click, i don't know if it's too many mounts that's the issue, or if it's registering as a shift right click for some reason.

**Comment by Azuriuz** [comment]
oh also in the item's description it still refers to it as an ocarina
not sure if that can be edited

**Comment by Shadowclaimer** [comment]
Its a strange thing, there's multiple modes you have to swap between. One is to set an active, one to summon, or something.

The localization is a good point, I can fix that.

**Comment by Shadowclaimer** [comment]
Mess with the modes and make sure this is an active bug please.

**Comment by Azuriuz** [comment]
It was a mode issue, thank you for pointing that out.
Also for your edification, it teleports ALL nearby saddled mounts when activated so... Make sure to only leave 1 mount saddled when using, or if anyone asks or has an issue with too many mounts.
