### ISSUE TITLE
Beds

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/RTTS-Atum#28]
can only be crafted with wool, but the atum wood works with it, just not linen. This is a non issue because of string, but if you eventually wish to remove string crafting wool, or flax making string etc, this recipe will need to be changed

**Comment by Shadowclaimer** [comment]
Linen/Wool Dictionary is live with Forge 2831, the pack will be updating to 2833 soon which should correct this.

This should be reported on the Atum 2 Issue Tracker as well.
