### ISSUE TITLE
chisels and bits

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/RTTS-Atum#29]
bits bags recipe requires wool
patterns require vanilla paper

suggestion:
change the mirror pattern from using glowstone dust to something easier to get like ectoplasm. (patterns should honestly be craftable pretty early game, but in atum you basically can't craft the mirror pattern til you find a lighthouse, and even then you wouldn't want to waste the glowstone; it just doesn't seem cost efficient for something so minor to require something so rare, feels bad man)

**Comment by Shadowclaimer** [comment]
I used the ones from the test server but they didn't work properly due to still missing overworld stuff.

I'll probably change it to ectoplasm.
