### ISSUE TITLE
Champions spawning WAY MORE in singleplayer

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/RTTS-Atum#30]
Not sure if this is a bug but i just played singleplayer to test something and nearly every mob was a champion. The pharoahs were champions, the mummies they summoned, champions.
even just looking around, groups of champions would spawn and it was honestly rare to see one that wasn't sparkling.

**Comment by Shadowclaimer** [comment]
That's strange, likely something to do with how we distribute configs. I'll look into it.
