### ISSUE TITLE
Silk Touch Spawners Plz

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/RTTS-Atum#34]
There's no way in atum to make a mob grinder, short of building a giant redstone contraption (because no water outside of oasis, and no spawns inside oasis). I suggest being able to silk touch spawners. This mod gives you the ability to config the option, and says it has configs for modded mob spawners etc. 

https://minecraft.curseforge.com/projects/silk-spawners-forge-edition

Note: I know you are worried about people gaming things, but I was talking to tay the other day about possible balancing options and brainstormed- I have a suggestion. Bone storms, and wraiths fly, and thus you can't really make a grinder for them very well, so don't allow access to their spawners. Similarly, there's no reason to allow use of BOTH barbarian, and brigand spawners since they have similar drops. 
You could just make it in the configs so that only forsaken, mummy, barbarian, and nomad spawners can be picked up. That's only 4 mobs and people wouldn't be able to game it much. You could also, if the configs allow, specify that you can't pick them up in pyramids (i don't know if that's a thing) which would mean only half the spawners would be pickuppable, the ones that are don't drop anything SUPER worth. You could maybe farm for coins, or bones, or barbarian swords XD
Not to mention even if someone knows how to make like, a god grinder with a bunch of types of spawners (like me)... only half of them would work at a time, because they are day/night locked. I think these balance changes would let people build an xp farm if they wanted, but also it'd make it harder to just game it if there's only 4 spawners that are pickuppable. It means you have to go through the effort of getting silk touch (could say its pickuppable from diamond tier only too), then they'd only have 4 options, and then they'd have to find an oasis and go through the trouble of building a spawner. I feel like that's balanced, and would allow players to build a mob grinder without allowing them to be too op.

I hope you'll look into it, I think it'll be a great addition to the modpack!

**Comment by Shadowclaimer** [comment]
There's another mod I'm looking at called Apotheosis with its own spawner system I really like that I'll be configging to hell and back. I think you'll like it.
