### ISSUE TITLE
backpack recipe issue

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/RTTS-Atum#40]
nei says it's sposed to use wool. It doesn't. I tired linen too just to see, but it doesn't use that either

**Comment by Shadowclaimer** [comment]
I just made one on stream with a linen block.

**Comment by Azuriuz** [comment]
whut, but it didnt work when i tried it D:

**Comment by Shadowclaimer** [comment]
Its a JEI issue and should be fixed when I push the next configs.
