### ISSUE TITLE
New Forge messed up some recipe compatability

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/RTTS-Atum#48]
Looking into it further, but it looks like it reads linen as wool now. Which is cool, except that when you try to dye linen it turns it into wool of that color. You can also use linen to make wool carpets etc. Not sure what all else this applies to, I assume this is because new forge updated ore dictionary?
![2019-05-20_17 29 07](https://user-images.githubusercontent.com/50718369/58053248-f884c280-7b24-11e9-8eb1-3adaddcc86e5.png)

**Comment by Shadowclaimer** [comment]
Fixed in new Atum version
