### ISSUE TITLE
Traps triggering from the wrong side

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/RTTS-Atum#49]
Not sure if this is the same issue with traps, but since the update they trigger from behind as well
![2019-05-20_18 42 12](https://user-images.githubusercontent.com/50718369/58056507-4999b400-7b2f-11e9-896b-fc269c6a39cc.png)

**Comment by Azuriuz** [comment]
I'm also still getting weird issues where traps trigger when disabled, but there's also ALOT of lag on the server atm, not sure if that could be the source of the issue

**Comment by Azuriuz** [comment]
Arrow traps having xray also seems to not be fixed. 
![2019-05-20_19 00 07](https://user-images.githubusercontent.com/50718369/58057067-91213f80-7b31-11e9-99e9-e7d8f3b61693.png)

**Comment by Shadowclaimer** [comment]
Atum Bug, likely fixed in new Atum versions.
