### ISSUE TITLE
Limestone Chest Bugs 

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/RTTS-Atum#50]
![2019-05-20_19 02 29](https://user-images.githubusercontent.com/50718369/58057191-05f47980-7b32-11e9-8b2d-aab82ebc1009.png)
Limestone chests haven't displayed as a single chest in a while. They just default to half of a double chest.
Also when breakings a limestone double chest, the back side of the remaining chest glitches and turns invisible (will try to get a screenshot of this as well when possible)

**Comment by Azuriuz** [comment]
![2019-05-20_19 04 34](https://user-images.githubusercontent.com/50718369/58057211-20c6ee00-7b32-11e9-8ac8-1420062839cd.png)
got it!

**Comment by Azuriuz** [comment]
![2019-05-20_19 04 34](https://cdn.discordapp.com/attachments/443135313481695252/580996767986745347/2019-05-23_15.22.38.png)
Posted by 4cqker in discord, not sure if this is a modded issue or the mod itself now.

**Comment by Shadowclaimer** [comment]
Fixed in Atum 2.0.8
