### ISSUE TITLE
Thin Crystal Glass Texture

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/RTTS-Atum#63]
It doesn't have one, like numbers show but otherwise it's just missing. The texture shows in NEI but not in inventories or crafting recipes.
![2019-05-25_03 45 42](https://user-images.githubusercontent.com/50718369/58366400-a5ea3400-7e9f-11e9-9d46-17a60d3f9af1.png)

**Comment by Shadowclaimer** [comment]
This is an Atum bug, I messaged Girafi about this one already.

**Comment by Shadowclaimer** [comment]
Will be fixed in a future Atum release (NOT 2.0.9)
