### ISSUE TITLE
Stonewarden registered as monster?

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/RTTS-Atum#64]
There's no baddies nearby, that I can find..
![2019-05-25_05 10 27](https://user-images.githubusercontent.com/50718369/58367284-8c4ee980-7eab-11e9-8203-cab377ad54f2.png)

**Comment by Shadowclaimer** [comment]
This would be an Atum bug. Does this occur with Friendly Stoneguard as well?

**Comment by Shadowclaimer** [comment]
Will be fixed in a future Atum release (NOT 2.0.9)

**Comment by Azuriuz** [comment]
Sorry, I meant to post it and the crystal glass in atum github, i was very tired last night
I hadn't tried with friendly stoneguard, just stonewarden but i can test stoneguard tonight when i get home if still needed?

**Comment by Shadowclaimer** [comment]
You're fine, Girafi checked it and fixed it, we hsould test it with normal Stoneguard to be safe though.
