### ISSUE TITLE
Linen Block turns into Wool

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/RTTS-Atum#79]
If you dye a linen block it turns into wool of that color instead of linen of that color.
![2019-06-08_02 22 08](https://user-images.githubusercontent.com/50718369/59143001-799ce000-8994-11e9-972e-b828708a1538.png)
![2019-06-08_02 22 51](https://user-images.githubusercontent.com/50718369/59143002-799ce000-8994-11e9-86d5-25967e4e5f07.png)

**Comment by Shadowclaimer** [comment]
This is an issue with base Atum on update. Its being looked into and Girafi is working on it.
