### ISSUE TITLE
Chiseling Glass

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/RTTS-Atum#82]
Ok so vanilla glass can be chiseled, but Atum glass, both crystal and stained, cannot be chiseled. Neither can glassentials; which kind of makes sense but is it possible for at least crystal glass types to be chiselable? I'm sure I'm not the only player who will like going crazy with stained glass.

![2019-06-10_00 19 25](https://user-images.githubusercontent.com/50718369/59172405-c3f99a80-8b15-11e9-87b1-49aeabfc5369.png)

**Comment by Shadowclaimer** [comment]
I'm not sure what does this, might want to check with Atum 2's main git instead of here.
