### ISSUE TITLE
Atum's Homecoming no longer Loads World

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/RTTS-Atum#84]
It worked fine before, it works fine in singleplayer, and in singleplayer/server in regular Atum so this is JUST the modpack server it's having an issue on. Girafi confirmed it's not an Atum Bug. It might have happened from the last server update, unsure, as it worked fine before.

The artifact takes you home, but the chunks around you do not load. You can run (not free floating in space) but none of the textures for things around you load.

**Comment by TopPercentageRattata** [comment]
Happened to me before update as well. F3+A fixed it

**Comment by Shadowclaimer** [comment]
Yea I'm not sure what's causing this. Likely something to do with the server and updating mods repeatedly.

We're going to have to do a world restart at some point and test a final version of the pack. Let me know if this is reproducible with it.
